package com.german.letterservice.util.constants;

public enum DangerousFileExtensions {
        ACTION,APK,APP,BAT,BIN,CMD,COM,COMMAND,CPL,CSH,EXE,GADGET,INF,INS,
    INX,IPA,ISU,JOB,JSE,KSH,LNK,MSC,MSI,MSP,MST,OSX,OUT,PAF,PIF,PRG,PS1,REG,
    RGS,RUN,SCR,SCT,SHB,SHS,U3P,VB,VBE,VBS,VBSCRIPT,WORKFLOW,WS,WSF,WSH,
    A6P,AC,ACC,ACR,ACTM,AHK,AIR, ARSCRIPT,AS,ASB,AWK,AZW2,BEAM,BTM, CEL,CELX,
    CHM,COF,CRT,DEK,DLD,DMC,DOCM,DOTM,DXL,EAR,EBM,EBS,EBS2,ECF,EHAM,ELF,ES,
    EX4,EXOPC,EZS,FAS,FKY,FPI,FRS,FXP,GS,HAM,HMS,HPF,HTA,IIM,IPF,ISP,JAR,
    JS,JSX,KIX,LO,LS,MAM,MCR,MEL,MPX,MRC,MS,MXE,NEXE,OBS,ORE,OTM,PEX,PLX,
    POTM,PPAM,PPSM,PPTM,PRC,PVD,PWC,PYC,PYO,QPX,RBX,ROX,RPJ,S2A,SBS,SCA,
    SCAR,SCB,SCRIPT,SMM,SPR,TCP,THM,TLB,TMS,UDF,UPX,URL,VLX,VPM,WCM,
    WIDGET,WIZ,WPK,WPM,XAP,XBAP,XLAM,XLM,XLSM,XLTM,XQT,XYS,ZL9
}
